# Import numpy Library

In [1]:
import numpy as np

Basics of Numpy

Default size is int64, but we can change size if values or array is simple, as below.

In [2]:
a = np.array([1,2,3], dtype = 'int16')
print (a)

[1 2 3]


In [3]:
a.dtype

dtype('int16')

In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print (b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
b.dtype

dtype('float64')

In [6]:
# For Dimension of array
a.ndim

1

In [7]:
# Get shape, in (Row, Column) format
b.shape

(2, 3)

In [8]:
# Get size
a.itemsize

2

In [9]:
# as b array is float dtype(data type) so it has bigger in size comparing to int type
b.itemsize

8

In [10]:
# Get total size, depending of int size of array, a.size * a.itemsize
a.nbytes

6

# Accessing/ Changing specific items, rows, columns etc 

In [11]:
a = np.array ([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# Get specific element from array [r, c]
a[1, 2]

10

In [13]:
# Get a specific row, : -> includes all column. 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a sepcific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [16]:
# Specify a value at certain location in array
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [17]:
a[:, 2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

# 3-D example 

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
b.ndim

3

In [20]:
# Get specific element (work outside in), 0 index pos is 1st array set, 1 index pos is 2nd row and 1 index pos is 4 
b[0,1,1]

4

In [21]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [22]:
# replace
b[:,1,:] = [[6,6],[8,8]]
b

array([[[1, 2],
        [6, 6]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of Arrays

In [23]:
# All 0s Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1s Matrix
c = np.ones((4,2,2),dtype = 'int32')
c

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Any other number
np.full((3,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [26]:
# Any other number (full_like), it takes shape of other array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal numbers
np.random.rand(4,2) 

array([[0.92256372, 0.31229884],
       [0.91727479, 0.25094463],
       [0.29038525, 0.36834417],
       [0.59589034, 0.92808545]])

In [28]:
# Random Integer values (start, end-> exclusive)
np.random.randint(-4,6, size=(3,3))

array([[-1,  0,  2],
       [ 2, -2, -2],
       [ 5, -4,  3]])

In [29]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [32]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be Careful when copying Arrays

In [33]:
a = np.array([1,2,3])
print ('First a is this',a)
b = a
b[0] = 100
print (b)
print (a)

First a is this [1 2 3]
[100   2   3]
[100   2   3]


In [34]:
# copy array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print (b)

[1 2 3]
[100   2   3]


# Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a - 2

array([-1,  0,  1,  2])

In [38]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [41]:
a ** 2

array([ 1,  4,  9, 16])

In [42]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [43]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [44]:
# Find the determinant(linear algebra--> linalg.det)
c = np.identity(3)
np.linalg.det(c)

1.0

In [45]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

## Determinant
## Trace
## Singular Vector Decomposition
## Eigenvalues
## Matrix Norm
## Inverse
## Etc...

# Statistics

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats)

6

In [49]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [50]:
np.max(stats, axis = 1)

array([3, 6])

In [51]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [52]:
np.min(stats, axis = 1)

array([1, 4])

In [53]:
np.sum(stats)

21

In [54]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [55]:
np.sum(stats, axis = 1)

array([ 6, 15])

## Reorganizing Arrays

In [56]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [57]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous 

## Load data from file 

In [60]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [61]:
# convert float numbers to int in array
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [62]:
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [67]:
filedata = filedata.astype('int32')
print (filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean masking and indexing 

In [63]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [69]:
# on filedata inside index bracket pass filedata to see which values are greater than 50 
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [71]:
# Index with list in numpy, [1,2,8] are the index postion of array a
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [76]:
np.any(filedata > 50,axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [78]:
# As this return all numbers i.e, no.s in 3 rows are > 50 
np.all(filedata > 50,axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [79]:
np.all(filedata > 50,axis = 1)

array([False, False, False])

In [82]:
((filedata > 50) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [84]:
# Negation of upper statement
(~((filedata > 50) & (filedata <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])